BOARD_TAG = pro5v328
#!! May need adjustment
ARDUINO_PORT = /dev/ttyUSB0
USER_LIB_PATH = .
ARDUINO_LIBS = dfplayer SoftwareSerial
ARDUINO_DIR = /usr/share/arduino
include /usr/share/arduino/Arduino.mk
